version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
<<<<<<< HEAD
      # Type the command to log in to your Docker Hub account here.
=======
      # Type the command to log in to your Docker Hub account here.          
>>>>>>> 4e9c45015217f864bdd454bc797a556d1980421d
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -PbuildDocker
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
