version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/*.jar
