version: '2'
services:
  config-server:
    image: mszarlinski/spring-petclinic-config-server
    container_name: config-server
    mem_limit: 1024M

  discovery-server:
    image: mszarlinski/spring-petclinic-discovery-server
    container_name: discovery-server
    mem_limit: 1024M
    links:
     - config-server
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

  customers-service:
    image: mszarlinski/spring-petclinic-customers-service
    container_name: customers-service
    mem_limit: 1024M
    links:
     - config-server
     - discovery-server
     - tracing-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

  visits-service:
    image: mszarlinski/spring-petclinic-visits-service
    container_name: visits-service
    mem_limit: 1024M
    links:
     - config-server
     - discovery-server
     - tracing-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

  vets-service:
    image: mszarlinski/spring-petclinic-vets-service
    container_name: vets-service
    mem_limit: 1024M
    links:
     - config-server
     - discovery-server
     - tracing-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

  api-gateway:
    image: mszarlinski/spring-petclinic-api-gateway
    container_name: api-gateway
    mem_limit: 1024M
    links:
     - config-server
     - discovery-server
     - customers-service
     - visits-service
     - vets-service
     - tracing-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8080:8080

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 256M
    ports:
     - 9411:9411

  admin-server:
    image: mszarlinski/spring-petclinic-admin-server
    container_name: admin-server
    mem_limit: 1024M
    links:
     - config-server
     - discovery-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
